;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="GameplayCue.Sounds.Boss",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Sounds.Boss.Rampage.Special",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Sounds.Boss.Rampage.Woosh",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Sounds.Boss.Robot.Basic",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Sounds.Boss.Robot.Special",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Sounds.Death.Enemy",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Sounds.Fire.Drongo",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Sounds.Fire.Rifle",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Sounds.Fire.Wraith",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Sounds.Hit.Enemy",DevComment="")

